version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Entered the install phase...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - ls
#     - aws s3 cp build/index.html s3://web1project --acl public-read
      - aws s3 cp build/index.html s3://web1project
  post_build:
      commands:
      - echo "Deployed to S3"
#       - aws s3 cp build/ s3://web1project/
artifacts:
  files:
    - '**/*'
