version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Entered the install phase...
      - npm install
  build:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Build started on `date`
      - npm run build
